### ISSUE TITLE
Entry point in array

### ISSUE THREAD

**Issue by aravindet** [adierkens/webpack-inject-plugin#5]
#3 Re-ordered the loaders so the injected script runs second-last.

This is causing problems with hot-module-reload. When using HMR, the main application code is second-last; the last entry is `webpackHotDevClient.js`. We need the injected code to run before the main application.

Would you be open to restoring the behaviour where the injection happens as early as possible? Alternately, perhaps the injection point could be configurable.

**Comment by adierkens** [comment]
I like the idea of making it configurable, with some sort of sane default. I had changed it originally b/c I needed the injected code to run after our polyfills, so having it be the first entry was problematic. 

Feel free to take a stab at implementing the config option if you want. Otherwise I can probably get to it in the next few days.

**Comment by adierkens** [comment]
Just publish [`0.5.0`](https://github.com/adierkens/webpack-inject-plugin/releases/tag/0.5.0) which enables you to change the injection entry order through a config option. 

Let me know if you have any issues with it 😄
